package com.mongs.wear.domain.error

enum class ClientErrorCode : ErrorCode {
    MQTT_EVENT_CONNECT_FAIL,
    MQTT_EVENT_PAUSE_CONNECT_FAIL,
    MQTT_EVENT_DISCONNECT_FAIL,
    MQTT_EVENT_SUBSCRIBE_FAIL,
    MQTT_EVENT_UNSUBSCRIBE_FAIL,
    MQTT_BATTLE_CONNECT_FAIL,
    MQTT_BATTLE_DISCONNECT_FAIL,
    MQTT_BATTLE_SUBSCRIBE_FAIL,
    MQTT_BATTLE_UNSUBSCRIBE_FAIL,
    MQTT_BATTLE_PRODUCE_FAIL,
}